const data = {
    "Kaise Mujhe (Instrumental)" :"A. R. Rahman - Kaise Mujhe",
    "Khwaja Mere Khwaja" : "A.R.Rahman - Khwaja Mere Khwaja",
    "Nashe Si Chadh Gayi" : "Akula 🇺🇸 - Nashe Si Chadh Gayi",
    "Naina Da Kya Kasoor" : "Amit Trivedi - Naina Da Kya Kasoor",
    "Galliyan" : "Ankit Tiwari - Galliyan",
    "Ae Dil Hai Mushkil Title Track" : "Arijit Singh - Ae Dil Hai Mushkil - MyMp3Song.info",
    "Sawan Aaya Hai" : "Arijit Singh - Sawan Aaya Hai",
    "Uska Hi Banana (From \"1920 Evil Returns\")" : "Arijit Singh - Uska Hi Banana - MusikMaza.Com",
    "Chale Aana (From \"De De Pyaar De\")" : "Armaan Malik - Chale Aana",
    "Akh Lad Jaave (From \"Loveyatri\")" : "Asees Kaur,Badshah,Jubin Nautiyal, - Akh Lad Jaave - Loveratri-(Mr-Song.Com)",
    "Pehli Nazar Mein" : "Atif Aslam - Pehli Nazar Mein",
    "Tera Hone Laga Hoon" : "Atif Aslam - Tera Hone Laga Hoon",
    "Kar Gayi Chull" : "Badshah - Chull - Fazilpuria",
    "Paagal" : "Badshah - Paagal",
    "She Move It Like" : "Badshah - She Move It Like",
    "Wakhra Swag" : "Badshah - Wakhra Swag",
    "Proper Patola" : "Badshah, Diljit Dosanjh, Aastha Gill - Proper Patola",
    "Chand Sifarish" : "Jatin-Lalit - Chand Sifarish",
    "The Humma Song" : "Jubin Nautyal, Shashaa Tirupati, Tanishk Bagchi, Badshah, A.R. Rahman - The Humma Song",
    "Kambakkht Ishq" : "K.K. & Sunidhi Chauhan - Kambakkht Ishq",
    "Tum Hi Ho" : "Kamil Munir - Tum Hi Ho",
    "Kabhi Khushi Kabhie Gham" : "Lata Mangeshkar - Kabhi Khushi Kabhie Gham (Sad Version 2)",
    "Te Amo (Para Siempre)" : "Mohit Chauhan - Te Amo (Reprise)",
    "Yaad Piya Ki Aane Lagi" : "Neha Kakkar - Yaad Piya Ki Aane Lagi 320Kbps- MrPaji.com (iPlayer.fm)",
    "O Saki Saki (From \"Batla House\")" : "Neha Kakkar feat.Tulsi Kumar & B Praak - O Saki Saki (OST Batla House)",
    "Mauja Hi Mauja" : "Pritam - Mauja Hi Mauja (remix)",
    "Sanu Ek Pal Chain (From \"Raid\")" : "Rahat Fateh Ali Khan - Sanu_Ek_Pal_Chain_Raid",
    "Kal Ho Naa Ho" : "Shankar-Ehsaan-Loy - Kal Ho Naa Ho",
    "Chikni Chameli" : "Shreya Ghoshal - Chikni Chameli (общая постановка)",
    "Nagada Sang Dhol" : "Shreya Ghoshal - Nagada Sang Dhol (feat. Osman Mir)",
    "Wada Raha" : "Shreya Ghoshal - Wada Raha",
    "Saathiya" : "Sonu Nigam - Saathiya",
    "Shukran Allah" : "Sonu Nigam - Shukran Allah (feat. Shreya Ghosal & Salim Merchant)",
    "Beedi (From \"Omkara\")" : "sukhwinder-singh-dorogi-indii-sunidhi-chauhan-beedi",
    "Tere Naam" : "sukhwinder-singh-lagan-lagi.....-tere-naam",
    "Kamli" : "Sunidhi Chauhan - Kamli",
    "Balam Pichkari" : "Vishal Dadlani - Balam Pichkari",
    "Chaar Botal Vodka (From \"Ragini Mms 2\")" : "Yo Yo Honey Singh - Chaar Botal Vodka (vk.com_newmuzon)",
    "Dheere Dheere" : "Yo Yo Honey Singh - Dheere Dheere - DJMaza.Info",
    "Love Dose" : "Yo Yo Honey Singh - Love Dose - Desi Kalakaar",
    "Lungi Dance" : "Yo Yo Honey Singh - Lungi Dance",
}

export { data };